---

- name: copy  spark-history.service
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'spark-history.service.j2', dest: '/etc/systemd/system/spark-history.service'  }
  when: >
    inventory_hostname in groups['spark_master'] and
    (groups['spark_history'].index(inventory_hostname) == 0 or groups['spark_history'].index(inventory_hostname) == 1)
  notify: restart start_history

- name: Reload service files
  systemd:
    daemon_reload: true




