---

- name: copy worker files
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode="0755"
  loop:
     - { src: 'spark-worker-1.service.j2', dest: '/etc/systemd/system/spark-worker-1.service'  }
  when: >
    inventory_hostname in groups['spark_worker']
    and  number_of_spark_worker_per_node  == 1
  notify: 
     - restart start_worker_1


- name: copy workers files3yy
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode="0755"
  loop:
     - { src: 'spark-worker-1.service.j2', dest: '/etc/systemd/system/spark-worker-1.service'  }
     - { src: 'spark-worker-2.service.j2', dest: '/etc/systemd/system/spark-worker-2.service'  }


  when: >
    inventory_hostname in groups['spark_worker']
    and  number_of_spark_worker_per_node  == 2
  notify: 
    - restart start_worker_1  
    - restart start_worker_2  

- name: copy workers  files
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode="0755"
  loop:
     - { src: 'spark-worker-1.service.j2', dest: '/etc/systemd/system/spark-worker-1.service'  }
     - { src: 'spark-worker-2.service.j2', dest: '/etc/systemd/system/spark-worker-2.service'  }
     - { src: 'spark-worker-3.service.j2', dest: '/etc/systemd/system/spark-worker-3.service'  }
  when: >
    inventory_hostname in groups['spark_worker']
    and  number_of_spark_worker_per_node  == 3
  notify: 
    - restart start_worker_1  
    - restart start_worker_2  
    - restart start_worker_3  

- name: copy workers files
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode="0755"
  loop:
     - { src: 'spark-worker-1.service.j2', dest: '/etc/systemd/system/spark-worker-1.service'  }
     - { src: 'spark-worker-2.service.j2', dest: '/etc/systemd/system/spark-worker-2.service'  }
     - { src: 'spark-worker-3.service.j2', dest: '/etc/systemd/system/spark-worker-3.service'  }
     - { src: 'spark-worker-4.service.j2', dest: '/etc/systemd/system/spark-worker-4.service'  }
  when: >
    inventory_hostname in groups['spark_worker']
    and  number_of_spark_worker_per_node  == 4
  notify: 
    - restart start_worker_1  
    - restart start_worker_2  
    - restart start_worker_3  
    - restart start_worker_4  

- name: Reload service files
  systemd:
    daemon_reload: true
