- name:  create  jceks password
  shell: 'export JAVA_HOME={{ java_home }}; /opt/hadoop/bin/hadoop credential create  {{ item }}'
  loop:
       - 'javax.jdo.option.ConnectionUserName -value {{ db_user }} -provider {{ jceks_provider }}'
       - 'javax.jdo.option.ConnectionPassword -value {{ db_password }} -provider {{ jceks_provider }}'
       - 'fs.s3a.access.key -value {{ fs_s3a_access_key }} -provider {{ jceks_provider }}'
       - 'fs.s3a.secret.key -value {{ fs_s3a_secret_key }} -provider {{ jceks_provider }}'
  ignore_errors: yes


- name: adjust secret.jceks
  file:
     path: '{{ item }}'
     group: '{{ jceks_group }}'
     mode: '0640'
  loop:
     - /usr/lib/java/secret.jceks
     - /usr/lib/java/.secret.jceks.crc

- name: create  {{ lockbox_dir }}     
  file:
      path: '{{ lockbox_dir }}'   
      state:  directory
      group: '{{ application_group }}'

- name: copy lockbox files 
  template: src='{{ item.src }}' dest='{{ item.dest }}'  group='{{ application_group }}' mode=0650
  loop:
     - { src: 'decrypt_lockbox.sh.j2', dest: '{{ lockbox_dir }}/decrypt_lockbox.sh' }       
     - { src: 'encrypt_lockbox.sh.j2', dest: '{{ lockbox_dir }}/encrypt_lockbox.sh' }       
     - { src: '{{ lockbox_env }}.j2', dest: '{{ tmpfs_dir }}/{{ lockbox_env }}' }

- name: encrypt {{ lockbox_env }}    
  shell: '{{ lockbox_dir }}/encrypt_lockbox.sh'


- name: create  {{ trino_password_dir }}     
  file:
      path: '{{ trino_password_dir }}'   
      state:  directory
      group: '{{ trino_group }}'
      mode: 0750

- name: Add defualt user for  trino
  shell: '{{ item }}' 
  loop:
     - 'htpasswd -c -b -B -C 10 {{ trino_password_file }}  {{ trino_user }} {{ trino_password }}'      
     - 'htpasswd -c -b -B -C 10 {{ trino_password_file }}  {{ superset_admin_user }} {{ superset_admin_password }}'      
